from datetime import timedelta

from django.test import TestCase
from django.utils import timezone

from tracking.models import ShipmentStatus, TrackingEvent
from .factories import make_shipment


class TrackingNumberTests(TestCase):
    def test_tracking_number_autogenerated_and_unique(self):
        s1 = make_shipment()
        s2 = make_shipment()
        self.assertEqual(len(s1.tracking_number), 12)
        self.assertTrue(s1.tracking_number.isdigit())
        self.assertNotEqual(s1.tracking_number, s2.tracking_number)


class NoFkFieldsTests(TestCase):
    def test_sender_and_recipient_are_plain_fields_not_relations(self):
        shipment = make_shipment(sender_name="Emeka Nwosu", recipient_name="Fatima Bello")
        self.assertEqual(shipment.sender_name, "Emeka Nwosu")
        self.assertEqual(shipment.recipient_name, "Fatima Bello")

    def test_route_is_a_plain_list_of_strings(self):
        shipment = make_shipment(
            origin="Lagos Hub", destination="Kano Hub", stops=["Ibadan Hub"]
        )
        self.assertEqual(shipment.route, ["Lagos Hub", "Ibadan Hub", "Kano Hub"])
        self.assertEqual(shipment.origin, "Lagos Hub")
        self.assertEqual(shipment.destination, "Kano Hub")


class StatusSyncTests(TestCase):
    def setUp(self):
        self.origin = "Origin Hub"
        self.destination = "Destination Hub"
        self.shipment = make_shipment(origin=self.origin, destination=self.destination)

    def test_creating_event_updates_status_and_location(self):
        TrackingEvent.objects.create(
            shipment=self.shipment,
            event_type=ShipmentStatus.PICKED_UP,
            location=self.origin,
        )
        self.shipment.refresh_from_db()
        self.assertEqual(self.shipment.status, ShipmentStatus.PICKED_UP)
        self.assertEqual(self.shipment.current_location, self.origin)

    def test_backdated_event_does_not_overwrite_newer_status(self):
        now = timezone.now()
        TrackingEvent.objects.create(
            shipment=self.shipment,
            event_type=ShipmentStatus.PICKED_UP,
            location=self.origin,
            timestamp=now,
        )
        TrackingEvent.objects.create(
            shipment=self.shipment,
            event_type=ShipmentStatus.ARRIVED_AT_FACILITY,
            location=self.destination,
            timestamp=now + timedelta(hours=5),
        )
        # Backdated event, older than the ARRIVED_AT_FACILITY event above.
        TrackingEvent.objects.create(
            shipment=self.shipment,
            event_type=ShipmentStatus.DEPARTED_FACILITY,
            location=self.origin,
            timestamp=now + timedelta(hours=1),
        )
        self.shipment.refresh_from_db()
        self.assertEqual(self.shipment.status, ShipmentStatus.ARRIVED_AT_FACILITY)
        self.assertEqual(self.shipment.current_location, self.destination)

    def test_deleting_latest_event_reverts_status(self):
        TrackingEvent.objects.create(
            shipment=self.shipment,
            event_type=ShipmentStatus.PICKED_UP,
            location=self.origin,
        )
        latest = TrackingEvent.objects.create(
            shipment=self.shipment,
            event_type=ShipmentStatus.ARRIVED_AT_FACILITY,
            location=self.destination,
        )
        latest.delete()
        self.shipment.refresh_from_db()
        self.assertEqual(self.shipment.status, ShipmentStatus.PICKED_UP)
        self.assertEqual(self.shipment.current_location, self.origin)

    def test_deleting_all_events_resets_to_label_created(self):
        self.shipment.events.all().delete()
        self.shipment.refresh_from_db()
        self.assertEqual(self.shipment.status, ShipmentStatus.LABEL_CREATED)
        self.assertEqual(self.shipment.current_location, "")

    def test_current_location_keeps_last_known_when_latest_has_none(self):
        TrackingEvent.objects.create(
            shipment=self.shipment,
            event_type=ShipmentStatus.ARRIVED_AT_FACILITY,
            location=self.destination,
        )
        TrackingEvent.objects.create(
            shipment=self.shipment,
            event_type=ShipmentStatus.OUT_FOR_DELIVERY,
            location="",
            location_note="Ikeja, Lagos",
        )
        self.shipment.refresh_from_db()
        self.assertEqual(self.shipment.status, ShipmentStatus.OUT_FOR_DELIVERY)
        self.assertEqual(self.shipment.current_location, self.destination)

    def test_delivered_at_set_and_cleared(self):
        event = TrackingEvent.objects.create(
            shipment=self.shipment,
            event_type=ShipmentStatus.DELIVERED,
            location=self.destination,
        )
        self.shipment.refresh_from_db()
        self.assertIsNotNone(self.shipment.delivered_at)
        self.assertEqual(self.shipment.delivered_at, event.timestamp)

        event.delete()
        self.shipment.refresh_from_db()
        self.assertIsNone(self.shipment.delivered_at)

    def test_is_overdue_when_eta_passed_and_not_delivered(self):
        self.shipment.estimated_delivery = (timezone.now() - timedelta(days=1)).date()
        self.shipment.save(update_fields=["estimated_delivery"])
        self.assertTrue(self.shipment.is_overdue())

    def test_not_overdue_when_eta_in_future(self):
        self.shipment.estimated_delivery = (timezone.now() + timedelta(days=1)).date()
        self.shipment.save(update_fields=["estimated_delivery"])
        self.assertFalse(self.shipment.is_overdue())

    def test_not_overdue_once_delivered_even_if_eta_passed(self):
        self.shipment.estimated_delivery = (timezone.now() - timedelta(days=1)).date()
        self.shipment.save(update_fields=["estimated_delivery"])
        TrackingEvent.objects.create(
            shipment=self.shipment,
            event_type=ShipmentStatus.DELIVERED,
            location=self.destination,
        )
        self.shipment.refresh_from_db()
        self.assertFalse(self.shipment.is_overdue())


class VisitedLocationsTests(TestCase):
    def setUp(self):
        self.origin = "Origin Hub"
        self.waypoint = "Waypoint Hub"
        self.destination = "Destination Hub"
        self.shipment = make_shipment(origin=self.origin, destination=self.destination)

    def test_visited_locations_collapses_consecutive_duplicates_but_keeps_revisits(self):
        now = timezone.now()
        # origin (from LABEL_CREATED) -> waypoint -> waypoint (dup, collapsed)
        # -> origin (revisit, kept) -> destination
        TrackingEvent.objects.create(
            shipment=self.shipment,
            event_type=ShipmentStatus.ARRIVED_AT_FACILITY,
            location=self.waypoint,
            timestamp=now + timedelta(hours=1),
        )
        TrackingEvent.objects.create(
            shipment=self.shipment,
            event_type=ShipmentStatus.DEPARTED_FACILITY,
            location=self.waypoint,
            timestamp=now + timedelta(hours=2),
        )
        TrackingEvent.objects.create(
            shipment=self.shipment,
            event_type=ShipmentStatus.ARRIVED_AT_FACILITY,
            location=self.origin,
            timestamp=now + timedelta(hours=3),
        )
        TrackingEvent.objects.create(
            shipment=self.shipment,
            event_type=ShipmentStatus.ARRIVED_AT_FACILITY,
            location=self.destination,
            timestamp=now + timedelta(hours=4),
        )
        visited = self.shipment.visited_locations()
        self.assertEqual(
            visited,
            [self.origin, self.waypoint, self.origin, self.destination],
        )
        self.assertEqual(self.shipment.stop_count(), 4)
