# Generated by Django 5.2.17 on 2026-09-24 09:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(blank=True, db_index=True, max_length=12, unique=True)),
                ('sender_name', models.CharField(max_length=255)),
                ('sender_phone', models.CharField(max_length=32)),
                ('sender_line1', models.CharField(max_length=255)),
                ('sender_line2', models.CharField(blank=True, max_length=255)),
                ('sender_city', models.CharField(max_length=128)),
                ('sender_state', models.CharField(max_length=128)),
                ('sender_postal_code', models.CharField(blank=True, max_length=32)),
                ('sender_country', models.CharField(default='Nigeria', max_length=128)),
                ('recipient_name', models.CharField(max_length=255)),
                ('recipient_phone', models.CharField(max_length=32)),
                ('recipient_line1', models.CharField(max_length=255)),
                ('recipient_line2', models.CharField(blank=True, max_length=255)),
                ('recipient_city', models.CharField(max_length=128)),
                ('recipient_state', models.CharField(max_length=128)),
                ('recipient_postal_code', models.CharField(blank=True, max_length=32)),
                ('recipient_country', models.CharField(default='Nigeria', max_length=128)),
                ('service_level', models.CharField(choices=[('OVERNIGHT', 'Overnight'), ('EXPRESS', 'Express'), ('GROUND', 'Ground')], max_length=16)),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=8)),
                ('dimensions', models.CharField(blank=True, max_length=64)),
                ('declared_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('route', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('LABEL_CREATED', 'Label Created'), ('PICKED_UP', 'Picked Up'), ('ARRIVED_AT_FACILITY', 'Arrived at Facility'), ('DEPARTED_FACILITY', 'Departed Facility'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('DELIVERED', 'Delivered'), ('DELAYED', 'Delayed')], db_index=True, default='LABEL_CREATED', max_length=32)),
                ('current_location', models.CharField(blank=True, max_length=255)),
                ('estimated_delivery', models.DateField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('signed_by', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrackingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('LABEL_CREATED', 'Label Created'), ('PICKED_UP', 'Picked Up'), ('ARRIVED_AT_FACILITY', 'Arrived at Facility'), ('DEPARTED_FACILITY', 'Departed Facility'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('DELIVERED', 'Delivered'), ('DELAYED', 'Delayed')], max_length=32)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('location_note', models.CharField(blank=True, max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('delay_reason', models.CharField(blank=True, max_length=255)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='tracking.shipment')),
            ],
            options={
                'ordering': ['-timestamp', '-id'],
            },
        ),
    ]
