# Generated by Django 5.2.17 on 2026-09-25 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='recipient_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
