# Generated by Django 5.2.17 on 2026-09-25 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_shipment_recipient_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='email_notifications_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
